name: DailyAyah
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    CURRENT_PROJECT_VERSION: 5
    MARKETING_VERSION: 1.0

targets:
  DailyAyahApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: App
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cufica.dailyayah
        CODE_SIGN_ENTITLEMENTS: App/DailyAyah.entitlements
        PRODUCT_NAME: DailyAyah
        INFOPLIST_FILE: App/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "P6FX9URFQ2"
    dependencies:
      - target: DailyAyahWidgetExtension

  DailyAyahWidgetExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Widget
      - path: App/Config
      - path: App/Models
      - path: App/Services
      - path: App/Storage
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cufica.dailyayah.widget
        CODE_SIGN_ENTITLEMENTS: Widget/DailyAyahWidget.entitlements
        PRODUCT_NAME: DailyAyahWidgetExtension
        INFOPLIST_FILE: Widget/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "P6FX9URFQ2"

schemes:
  DailyAyahApp:
    build:
      targets:
        DailyAyahApp: all
